# new: Phase 1 D1.3 -- docs/children.json is the only committed generated file; this keeps it fresh.
"""Fail when docs/children.json no longer matches what the generator would write.

The generated file is regenerated by the controller, never by a sandboxed run, so the failure
message carries the exact command and the diff.
"""
from __future__ import annotations

import difflib
from pathlib import Path

from studio import demos
from studio.demos import CHILDREN_INDEX_REL, REPO_ROOT, TS_GAMES_REL, render_children_index

REGENERATE = "regenerate: uv run python -m studio.demos index"


def stale_message(committed: str, fresh: str) -> str:
    diff = "".join(difflib.unified_diff(
        committed.splitlines(keepends=True), fresh.splitlines(keepends=True),
        "docs/children.json (committed)", "docs/children.json (regenerated)"))
    return f"docs/children.json is stale.\n{REGENERATE}\n{diff}"


def make_root(tmp_path: Path) -> Path:
    config = tmp_path / TS_GAMES_REL / "alpha" / "config.ts"
    config.parent.mkdir(parents=True)
    config.write_text("export default { gameId: 'alpha', label: 'Alpha', status: 'dev' };\n", encoding="utf-8")
    return tmp_path


def test_children_index_is_fresh() -> None:
    committed = (REPO_ROOT / CHILDREN_INDEX_REL).read_text(encoding="utf-8")
    fresh = render_children_index(REPO_ROOT)
    assert committed == fresh, stale_message(committed, fresh)


def test_stale_message_names_the_command_and_the_diff(tmp_path: Path) -> None:
    root = make_root(tmp_path)
    fresh = render_children_index(root)
    message = stale_message('{"version": 1, "children": []}\n', fresh)
    assert REGENERATE in message.splitlines()
    assert '+      "id": "alpha",' in message


def test_render_matches_write(tmp_path: Path) -> None:
    root = make_root(tmp_path)
    written = demos.write_children_index(root=root)
    assert written.read_text(encoding="utf-8") == render_children_index(root)
