import { 
  RawPartId, 
  WeaponId, 
  PartDefinition, 
  WeaponRecipe, 
  TechUpgrade, 
  GridTile,
  TileType,
  SectorData
} from '../types';

export const RAW_PARTS: Record<RawPartId, PartDefinition> = {
  chassis: {
    id: 'chassis',
    name: 'Receiver Chassis',
    shortName: 'CHS',
    cost: 5,
    color: '#3b82f6',
    accentColor: '#1d4ed8',
    icon: 'Layers',
    description: 'Milled aeronautical aluminum receiver block.',
    unlockedByDefault: true,
  },
  barrel: {
    id: 'barrel',
    name: 'Rifled Barrel',
    shortName: 'BRL',
    cost: 10,
    color: '#f59e0b',
    accentColor: '#d97706',
    icon: 'Wrench',
    description: 'Precision ported steel pressure barrel.',
    unlockedByDefault: false,
  },
  magazine: {
    id: 'magazine',
    name: 'Spring Magazine',
    shortName: 'MAG',
    cost: 5,
    color: '#10b981',
    accentColor: '#047857',
    icon: 'Package',
    description: 'Double-stack steel feed cassette.',
    unlockedByDefault: true,
  },
  stock: {
    id: 'stock',
    name: 'Recoil Stock',
    shortName: 'STK',
    cost: 15,
    color: '#8b5cf6',
    accentColor: '#6d28d9',
    icon: 'Shield',
    description: 'Reinforced glass-nylon adjustable buttstock.',
    unlockedByDefault: false,
  },
  optic: {
    id: 'optic',
    name: 'Precision Optic',
    shortName: 'OPT',
    cost: 25,
    color: '#ec4899',
    accentColor: '#be185d',
    icon: 'Eye',
    description: 'Nitrogen-purged illuminated variable reticle.',
    unlockedByDefault: false,
  },
};

export const WEAPON_RECIPES: Record<WeaponId, WeaponRecipe> = {
  pistol: {
    id: 'pistol',
    name: 'Duty Pistol',
    category: 'Handgun',
    requiredParts: { chassis: 1, magazine: 1, barrel: 0, stock: 0, optic: 0 },
    baseCost: 10,
    salePrice: 28,
    margin: 18,
    color: '#06b6d4',
    icon: 'Crosshair',
    description: 'Compact semi-automatic sidearm with high civilian & police demand.',
    craftTimeTicks: 3,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Tactical Shotgun',
    category: 'Scatter',
    requiredParts: { chassis: 1, barrel: 1, magazine: 1, stock: 0, optic: 0 },
    baseCost: 20,
    salePrice: 65,
    margin: 45,
    color: '#f59e0b',
    icon: 'Zap',
    description: 'Close-quarters smoothbore with high kinetic stopping power.',
    craftTimeTicks: 4,
    requiredTechId: 'tech_scattershot',
  },
  rifle: {
    id: 'rifle',
    name: 'Service Rifle',
    category: 'Rifle',
    requiredParts: { chassis: 2, barrel: 1, magazine: 1, stock: 0, optic: 0 },
    baseCost: 25,
    salePrice: 95,
    margin: 70,
    color: '#10b981',
    icon: 'Target',
    description: 'Standard infantry modular rifle with dependable military contract margins.',
    craftTimeTicks: 5,
    requiredTechId: 'tech_rifle_license',
  },
  smg: {
    id: 'smg',
    name: 'Tactical SMG',
    category: 'Special Ops',
    requiredParts: { chassis: 1, barrel: 1, magazine: 2, stock: 1, optic: 0 },
    baseCost: 40,
    salePrice: 150,
    margin: 110,
    color: '#8b5cf6',
    icon: 'Award',
    description: 'High-cyclic personal defense weapon for security details.',
    craftTimeTicks: 6,
    requiredTechId: 'tech_specops',
  },
  dmr: {
    id: 'dmr',
    name: 'Mil-Spec DMR',
    category: 'Precision',
    requiredParts: { chassis: 2, barrel: 2, magazine: 1, stock: 1, optic: 1 },
    baseCost: 80,
    salePrice: 320,
    margin: 240,
    color: '#ec4899',
    icon: 'Eye',
    description: 'Long-range designated marksman platform with premier defense margins.',
    craftTimeTicks: 8,
    requiredTechId: 'tech_precision',
  },
};

export interface BuildingDefinition {
  type: TileType;
  name: string;
  category: 'Logistics' | 'Production' | 'Power & Science' | 'Export & Utility';
  cost: number;
  powerUsage: number; // kW
  powerOutput: number; // kW
  operatingCost: number; // $/tick
  description: string;
  requiredTechId?: string;
}

export const BUILDING_DEFS: Record<TileType, BuildingDefinition> = {
  empty: {
    type: 'empty',
    name: 'Empty Lot',
    category: 'Export & Utility',
    cost: 0,
    powerUsage: 0,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Clear floor tile ready for building.',
  },
  conveyor: {
    type: 'conveyor',
    name: 'Conveyor Belt',
    category: 'Logistics',
    cost: 2,
    powerUsage: 0.1,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Directional conveyor transferring parts & weapons 1 tile per tick.',
  },
  splitter: {
    type: 'splitter',
    name: 'Belt Splitter',
    category: 'Logistics',
    cost: 15,
    powerUsage: 0.3,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Evenly alternates incoming items across 2 or 3 output lanes (50/50 balancer).',
    requiredTechId: 'tech_splitter',
  },
  merger: {
    type: 'merger',
    name: 'Belt Merger',
    category: 'Logistics',
    cost: 15,
    powerUsage: 0.3,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Seamlessly merges up to 3 incoming conveyor lines into 1 unified stream.',
    requiredTechId: 'tech_merger',
  },
  underground_entry: {
    type: 'underground_entry',
    name: 'Underground Tunnel',
    category: 'Logistics',
    cost: 25,
    powerUsage: 0.5,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Passes items underground for up to 4 tiles, allowing conveyor crossways without collisions.',
    requiredTechId: 'tech_underground',
  },
  underground_exit: {
    type: 'underground_exit',
    name: 'Tunnel Exit',
    category: 'Logistics',
    cost: 0,
    powerUsage: 0,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Subterranean conveyor exit point.',
  },
  crossing: {
    type: 'crossing',
    name: 'Conveyor Crossing',
    category: 'Logistics',
    cost: 20,
    powerUsage: 0.2,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Allows North-South and East-West conveyor lanes to intersect without mixing items.',
    requiredTechId: 'tech_crossing',
  },
  filter: {
    type: 'filter',
    name: 'Sorter / Filter Gate',
    category: 'Logistics',
    cost: 30,
    powerUsage: 0.5,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Routes configured part forward, diverting all other items 90° clockwise.',
    requiredTechId: 'tech_filter',
  },
  switch: {
    type: 'switch',
    name: 'Diverter Switch',
    category: 'Logistics',
    cost: 10,
    powerUsage: 0.2,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Toggleable two-way mechanical switch routing flow between two angles.',
  },
  spawner: {
    type: 'spawner',
    name: 'Intake Hopper / Buyer',
    category: 'Production',
    cost: 10,
    powerUsage: 0.5,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Injects parts from warehouse stock onto belts. Can be set to Auto-Buy from cash reserves.',
  },
  fitter: {
    type: 'fitter',
    name: 'Assembly Fitter',
    category: 'Production',
    cost: 25,
    powerUsage: 2.0,
    powerOutput: 0,
    operatingCost: 0.1,
    description: 'Takes raw parts from surrounding belts and crafts precision firearms.',
  },
  packer: {
    type: 'packer',
    name: 'Storefront Packer',
    category: 'Production',
    cost: 20,
    powerUsage: 1.0,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Inspects and packs finished firearms directly onto Storefront retail shelves.',
  },
  seller: {
    type: 'seller',
    name: 'Direct Export Port',
    category: 'Export & Utility',
    cost: 35,
    powerUsage: 1.5,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Instantly exports items/weapons to the global market for continuous $/sec cashflow.',
    requiredTechId: 'tech_export_port',
  },
  lab: {
    type: 'lab',
    name: 'R&D Research Lab',
    category: 'Power & Science',
    cost: 50,
    powerUsage: 4.0,
    powerOutput: 0,
    operatingCost: 0.2,
    description: 'Generates Research Points (+RP/s) continuously to unlock advanced technologies.',
    requiredTechId: 'tech_research_lab',
  },
  power_gen: {
    type: 'power_gen',
    name: 'Power Generator',
    category: 'Power & Science',
    cost: 40,
    powerUsage: 0,
    powerOutput: 25.0, // Generates 25 kW
    operatingCost: 0.1,
    description: 'Provides electrical power (kW) across the factory grid. Prevents brownout slowdowns.',
  },
  trash: {
    type: 'trash',
    name: 'Recycler / Incinerator',
    category: 'Export & Utility',
    cost: 5,
    powerUsage: 0.2,
    powerOutput: 0,
    operatingCost: 0,
    description: 'Safely eliminates jammed items and excess parts with a 50% scrap refund.',
  },
};

export const TECH_UPGRADES: TechUpgrade[] = [
  // --- TIER 1: PIONEER LOGISTICS & POWER ---
  {
    id: 'tech_splitter',
    name: 'Logistics Splitter',
    tier: 1,
    cost: 50,
    rpCost: 0,
    purchased: true,
    category: 'logistics',
    description: 'Unlocks 2-way & 3-way splitters to evenly divide single item lines into parallel production tracks.',
    icon: 'GitBranch',
  },
  {
    id: 'tech_merger',
    name: 'Logistics Merger',
    tier: 1,
    cost: 50,
    rpCost: 0,
    purchased: true,
    category: 'logistics',
    description: 'Unlocks conveyor mergers to combine multiple incoming feeds into one output line.',
    icon: 'GitMerge',
  },
  {
    id: 'tech_scattershot',
    name: 'Scattershot Tooling',
    tier: 1,
    cost: 100,
    rpCost: 20,
    purchased: false,
    category: 'weapons',
    description: 'Unlocks Rifled Barrel ($10) and Tactical Shotgun recipe ($65 sale, +$45 margin).',
    icon: 'Zap',
  },
  {
    id: 'tech_research_lab',
    name: 'Applied Science Lab',
    tier: 1,
    cost: 75,
    rpCost: 0,
    purchased: false,
    category: 'power',
    description: 'Unlocks the R&D Research Lab tile, generating steady Research Points (+RP/s) for advanced tech.',
    icon: 'Cpu',
  },

  // --- TIER 2: ADVANCED LOGISTICS & MIL-SPEC ---
  {
    id: 'tech_underground',
    name: 'Underground Conveyors',
    tier: 2,
    cost: 150,
    rpCost: 50,
    purchased: false,
    category: 'logistics',
    description: 'Enables underground tunnels up to 4 tiles long, bypassing crowded belts and machines.',
    icon: 'Minimize2',
    prerequisiteId: 'tech_research_lab',
  },
  {
    id: 'tech_crossing',
    name: 'Conveyor Crossings',
    tier: 2,
    cost: 120,
    rpCost: 40,
    purchased: false,
    category: 'logistics',
    description: 'Allows perpendicular conveyor belts to cross the same grid tile without mixing items.',
    icon: 'Plus',
    prerequisiteId: 'tech_splitter',
  },
  {
    id: 'tech_rifle_license',
    name: 'Service Rifle Blueprint',
    tier: 2,
    cost: 200,
    rpCost: 60,
    purchased: false,
    category: 'weapons',
    description: 'Unlocks 3-part Service Rifle recipe (2x Chassis + Barrel + Mag) ($95 sale, +$70 margin).',
    icon: 'Target',
    prerequisiteId: 'tech_scattershot',
  },
  {
    id: 'tech_export_port',
    name: 'Direct Export Port',
    tier: 2,
    cost: 180,
    rpCost: 50,
    purchased: false,
    category: 'market',
    description: 'Unlocks Direct Export Ports to sell finished firearms or parts immediately for high-velocity cashflow.',
    icon: 'TrendingUp',
    prerequisiteId: 'tech_research_lab',
  },
  {
    id: 'tech_fast_belts',
    name: 'High-Speed Belts Mk2',
    tier: 2,
    cost: 160,
    rpCost: 45,
    purchased: false,
    category: 'logistics',
    description: 'Industrial ball-bearing drives accelerate conveyor speed by 25%.',
    icon: 'FastForward',
  },

  // --- TIER 3: PRECISION SORTING & AUTOMATION ---
  {
    id: 'tech_filter',
    name: 'Sorter / Filter Gates',
    tier: 3,
    cost: 250,
    rpCost: 100,
    purchased: false,
    category: 'logistics',
    description: 'Programmable optical sorters route specific parts forward while deflecting others.',
    icon: 'Sliders',
    prerequisiteId: 'tech_underground',
  },
  {
    id: 'tech_specops',
    name: 'Tactical SMG License',
    tier: 3,
    cost: 300,
    rpCost: 120,
    purchased: false,
    category: 'weapons',
    description: 'Unlocks Recoil Stock ($15) and Tactical SMG recipe ($150 sale, +$110 margin).',
    icon: 'Award',
    prerequisiteId: 'tech_rifle_license',
  },
  {
    id: 'tech_power_mk2',
    name: 'Heavy Gas Turbine Mk2',
    tier: 3,
    cost: 350,
    rpCost: 150,
    purchased: false,
    category: 'power',
    description: 'Doubles power generator output from 25 kW to 50 kW per turbine unit.',
    icon: 'Zap',
    prerequisiteId: 'tech_research_lab',
  },
  {
    id: 'tech_expanded_shelf',
    name: 'Warehouse Shelf Expansion',
    tier: 3,
    cost: 280,
    rpCost: 80,
    purchased: false,
    category: 'market',
    description: 'Doubles storefront retail shelf capacity from 5 to 10 firearms per category.',
    icon: 'Layers',
  },

  // --- TIER 4: MIL-SPEC PRECISION & MEGA EXPANSION ---
  {
    id: 'tech_precision',
    name: 'Mil-Spec DMR License',
    tier: 4,
    cost: 500,
    rpCost: 250,
    purchased: false,
    category: 'weapons',
    description: 'Unlocks Precision Optic ($25) and Mil-Spec DMR ($320 sale, +$240 margin).',
    icon: 'Eye',
    prerequisiteId: 'tech_specops',
  },
  {
    id: 'tech_overclock',
    name: 'Fitter Overclocking Mk3',
    tier: 4,
    cost: 600,
    rpCost: 300,
    purchased: false,
    category: 'production',
    description: 'Unlocks Tier 3 machine upgrades on Fitters, reducing assembly craft duration by 40%.',
    icon: 'Cpu',
    prerequisiteId: 'tech_power_mk2',
  },
];

export const INITIAL_SECTORS: Record<string, SectorData> = {
  sector_a: {
    id: 'sector_a',
    name: 'Sector α: Alpha Works',
    tagline: 'Primary Small Arms & Handgun Machining',
    gridWidth: 12,
    gridHeight: 9,
    grid: Array.from({ length: 9 }, (_, y) =>
      Array.from({ length: 12 }, (_, x) => ({
        x,
        y,
        type: 'empty' as TileType,
        direction: 'E',
        isEnabled: true,
        tier: 1,
      }))
    ),
    items: [],
    unlocked: true,
    unlockCost: 0,
  },
  sector_b: {
    id: 'sector_b',
    name: 'Sector β: Heavy Munitions',
    tagline: 'Long Guns, Shotgun & Assault Rifle Lines',
    gridWidth: 12,
    gridHeight: 9,
    grid: Array.from({ length: 9 }, (_, y) =>
      Array.from({ length: 12 }, (_, x) => ({
        x,
        y,
        type: 'empty' as TileType,
        direction: 'E',
        isEnabled: true,
        tier: 1,
      }))
    ),
    items: [],
    unlocked: false,
    unlockCost: 500,
  },
  sector_c: {
    id: 'sector_c',
    name: 'Sector γ: High-Tech R&D',
    tagline: 'Advanced Optics, DMRs & Research Power Core',
    gridWidth: 12,
    gridHeight: 9,
    grid: Array.from({ length: 9 }, (_, y) =>
      Array.from({ length: 12 }, (_, x) => ({
        x,
        y,
        type: 'empty' as TileType,
        direction: 'E',
        isEnabled: true,
        tier: 1,
      }))
    ),
    items: [],
    unlocked: false,
    unlockCost: 1500,
  },
};

export interface FactoryPreset {
  id: string;
  name: string;
  description: string;
  tiles: Partial<GridTile>[];
}

export const PRESET_FACTORIES: FactoryPreset[] = [
  {
    id: 'preset_starter',
    name: 'Pistol Starter Assembly',
    description: 'Clean dual-hopper setup feeding a central Fitter and Packer.',
    tiles: [
      { x: 2, y: 3, type: 'power_gen', direction: 'E' },
      { x: 1, y: 4, type: 'spawner', spawnerPart: 'chassis', direction: 'E', isEnabled: true },
      { x: 1, y: 5, type: 'spawner', spawnerPart: 'magazine', direction: 'E', isEnabled: true },
      { x: 2, y: 4, type: 'conveyor', direction: 'E' },
      { x: 2, y: 5, type: 'conveyor', direction: 'N' },
      { x: 3, y: 4, type: 'fitter', fitterTargetRecipe: 'pistol', direction: 'E', isEnabled: true },
      { x: 4, y: 4, type: 'conveyor', direction: 'E' },
      { x: 5, y: 4, type: 'packer', direction: 'E', isEnabled: true },
    ],
  },
  {
    id: 'preset_splitter_balancer',
    name: 'Splitter Balancer Line',
    description: 'Single chassis stream divided across two parallel pistol fitters using a Splitter.',
    tiles: [
      { x: 1, y: 1, type: 'power_gen', direction: 'E' },
      { x: 1, y: 3, type: 'spawner', spawnerPart: 'chassis', direction: 'E', isEnabled: true },
      { x: 2, y: 3, type: 'splitter', direction: 'E', isEnabled: true },
      // Top branch
      { x: 2, y: 2, type: 'conveyor', direction: 'E' },
      { x: 3, y: 2, type: 'fitter', fitterTargetRecipe: 'pistol', direction: 'E', isEnabled: true },
      { x: 3, y: 1, type: 'spawner', spawnerPart: 'magazine', direction: 'S', isEnabled: true },
      { x: 4, y: 2, type: 'conveyor', direction: 'E' },
      // Bottom branch
      { x: 2, y: 4, type: 'conveyor', direction: 'E' },
      { x: 3, y: 4, type: 'fitter', fitterTargetRecipe: 'pistol', direction: 'E', isEnabled: true },
      { x: 3, y: 5, type: 'spawner', spawnerPart: 'magazine', direction: 'N', isEnabled: true },
      { x: 4, y: 4, type: 'conveyor', direction: 'E' },
      // Merged to packer
      { x: 5, y: 3, type: 'merger', direction: 'E', isEnabled: true },
      { x: 4, y: 2, type: 'conveyor', direction: 'S' },
      { x: 4, y: 4, type: 'conveyor', direction: 'N' },
      { x: 6, y: 3, type: 'packer', direction: 'E', isEnabled: true },
    ],
  },
  {
    id: 'preset_underground_highway',
    name: 'Underground Crossway & Export',
    description: 'Underground tunnels diving beneath intersecting conveyor lines directly to an Export Port.',
    tiles: [
      { x: 1, y: 2, type: 'power_gen', direction: 'E' },
      { x: 1, y: 3, type: 'lab', direction: 'E', isEnabled: true },
      { x: 1, y: 5, type: 'spawner', spawnerPart: 'chassis', direction: 'E', isEnabled: true },
      { x: 2, y: 5, type: 'underground_entry', direction: 'E', isEnabled: true },
      // Perpendicular line crossing over
      { x: 4, y: 3, type: 'spawner', spawnerPart: 'magazine', direction: 'S', isEnabled: true },
      { x: 4, y: 4, type: 'conveyor', direction: 'S' },
      { x: 4, y: 5, type: 'conveyor', direction: 'S' },
      { x: 4, y: 6, type: 'conveyor', direction: 'S' },
      // Underground emerges
      { x: 5, y: 5, type: 'underground_exit', direction: 'E', isEnabled: true },
      { x: 6, y: 5, type: 'fitter', fitterTargetRecipe: 'pistol', direction: 'E', isEnabled: true },
      { x: 7, y: 5, type: 'conveyor', direction: 'E' },
      { x: 8, y: 5, type: 'seller', direction: 'E', isEnabled: true },
    ],
  },
  {
    id: 'preset_factory_idle_mega',
    name: 'Factory Idle Integrated Complex',
    description: 'Complete integrated industrial layout with Power Generators, Research Labs, Splitters, Fitters, Packers, and Export Sellers.',
    tiles: [
      // Power & Science Hub
      { x: 1, y: 1, type: 'power_gen', direction: 'E' },
      { x: 2, y: 1, type: 'power_gen', direction: 'E' },
      { x: 3, y: 1, type: 'lab', direction: 'E', isEnabled: true },
      { x: 4, y: 1, type: 'lab', direction: 'E', isEnabled: true },

      // Main Line 1: Pistol & Shotgun Parallel Hub
      { x: 1, y: 3, type: 'spawner', spawnerPart: 'chassis', direction: 'E', isEnabled: true },
      { x: 2, y: 3, type: 'splitter', direction: 'E', isEnabled: true },
      { x: 3, y: 3, type: 'conveyor', direction: 'E' },
      { x: 4, y: 3, type: 'fitter', fitterTargetRecipe: 'pistol', direction: 'E', isEnabled: true },
      { x: 4, y: 2, type: 'spawner', spawnerPart: 'magazine', direction: 'S', isEnabled: true },
      { x: 5, y: 3, type: 'conveyor', direction: 'E' },
      { x: 6, y: 3, type: 'packer', direction: 'E', isEnabled: true },

      // Main Line 2: Shotgun Line
      { x: 2, y: 4, type: 'conveyor', direction: 'S' },
      { x: 2, y: 5, type: 'conveyor', direction: 'E' },
      { x: 3, y: 5, type: 'conveyor', direction: 'E' },
      { x: 4, y: 5, type: 'fitter', fitterTargetRecipe: 'shotgun', direction: 'E', isEnabled: true },
      { x: 4, y: 6, type: 'spawner', spawnerPart: 'barrel', direction: 'N', isEnabled: true },
      { x: 3, y: 6, type: 'spawner', spawnerPart: 'magazine', direction: 'E', isEnabled: true },
      { x: 5, y: 5, type: 'conveyor', direction: 'E' },
      { x: 6, y: 5, type: 'seller', direction: 'E', isEnabled: true },
    ],
  },
];
