"""register.py — register a new demo: write its config.ts (the glob registry picks it up; spec section c1)."""
from __future__ import annotations

import hashlib
import json
import zipfile
from pathlib import Path

from studio_mcp.demos.registry_files import next_order

PALETTE = ["#22d3ee", "#a78bfa", "#34d399", "#f472b6", "#fb923c", "#60a5fa", "#facc15", "#f87171"]


def color_for(slug: str) -> str:
    return PALETTE[int(hashlib.sha256(slug.encode("utf-8")).hexdigest(), 16) % len(PALETTE)]


def import_name(game_id: str) -> str:
    first, *rest = game_id.split("_")
    name = first + "".join(p[:1].upper() + p[1:] for p in rest) + "Config"
    return name if name[0].isalpha() else "demo" + name[0].upper() + name[1:]


def render_config_ts(game_id: str, slug: str, label: str, description: str, order: int) -> str:
    q = json.dumps
    return (
        "import type { GameConfig } from '../../engine/types';\n\n"
        "// Generated by `studio_mcp.demos import` from the AI Studio export's metadata.json.\n"
        "// Edit freely: re-imports never rewrite this file.\n"
        "const config: GameConfig = {\n"
        f"  gameId: {q(game_id)},\n"
        f"  order: {order},\n"
        f"  label: {q(label)},\n"
        f"  description: {q(description)},\n"
        f"  color: {q(color_for(slug))},\n"
        "  status: 'external',\n"
        f"  source: {{ kind: 'example', slug: {q(slug)} }},\n"
        f"  embedUrl: '/arcade/{game_id}/',\n"
        "};\n\n"
        "export default config;\n"
    )


def read_zip_metadata(zip_path: Path) -> dict:
    with zipfile.ZipFile(zip_path) as zf:
        names = [n for n in zf.namelist() if n == "metadata.json" or n.endswith("/metadata.json")]
        if not names:
            return {}
        data = json.loads(zf.read(min(names, key=len)).decode("utf-8", errors="replace"))
    return {k: data[k] for k in ("name", "description") if isinstance(data.get(k), str)}


def write_registration(repo_root: Path, game_id: str, slug: str, zip_path: Path) -> list[str]:
    """Register a brand-new demo. Returns the repo-relative files it changed (empty when already done)."""
    changed: list[str] = []
    meta = read_zip_metadata(zip_path)
    config = repo_root / "ts" / "src" / "games" / game_id / "config.ts"
    if not config.exists():
        config.parent.mkdir(parents=True, exist_ok=True)
        label = meta.get("name") or slug.replace("-", " ").title()
        config.write_text(render_config_ts(game_id, slug, label, meta.get("description", ""), next_order(config.parent.parent)), encoding="utf-8")
        changed.append(f"ts/src/games/{game_id}/config.ts")
    return changed
